# Generated by Django 6.0.6 on 2026-07-09 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='model',
            new_name='name',
        ),
    ]
